export const FILTER_OPTIONS = [
  {
    key: "CONTEST",
    category_id: 1,
    label: "공모전/대회",
    color: "bg-contestRed",
    tagBg: "bg-contestRed/30",
    textColor: "text-contestRed",
    borderColor: "border-contestRed",
  },
  {
    key: "LECTURE",
    category_id: 2,
    label: "특강",
    color: "bg-lectureBlue",
    tagBg: "bg-lectureBlue/30",
    textColor: "text-lectureBlue",
    borderColor: "border-lectureBlue",
  },
  {
    key: "SCHOLAR",
    category_id: 3,
    label: "장학",
    color: "bg-competitionYellow",
    tagBg: "bg-competitionYellow/30",
    textColor: "text-competitionYellow",
    borderColor: "border-competitionYellow",
  },
  {
    key: "ACTIVITY",
    category_id: 4,
    label: "대외활동",
    color: "bg-clubGreen",
    tagBg: "bg-clubGreen/30",
    textColor: "text-clubGreen",
    borderColor: "border-clubGreen",
  },
  {
    key: "MY",
    category_id: null,
    label: "북마크",
    color: "bg-clubGreen",
    tagBg: "bg-clubGreen/30",
    textColor: "text-clubGreen",
    borderColor: "border-clubGreen",
  },
];
